cocktails/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('recipes.urls')),
]

recipes/urls.py
"""Defines URL patterns for recipes"""

from django.urls import path
from . import views

app_name = 'recipes'
urlpatterns = [
    # HOME PAGE
    path('', views.index, name='index'),
    # PAGE THAT SHOWS ALL RECIPES
    path('recipes/', views.recipes, name='recipes'),
    # DETAIL PAGE FOR A SINGLE RECIPE
    path('recipes/<int:recipe_id>', views.recipe, name='recipe'),
    # PAGE FOR ADDING A NEW RECIPE
    path('new_recipe/', views.new_recipe, name='new_recipe'),
    # PAGE FOR EDITING A RECIPE
    path('recipes/<int:recipe_id>/edit_recipe', views.edit_recipe, name='edit_recipe'),
    # PAGE FOR ADDING AN INGREDIENT
    path('new_ingredient/<int:recipe_id>/', views.new_ingredient, name='new_ingredient'),
    # PAGE FOR EDITING INGREDIENTS
    path('edit_ingredient/<int:ingredient_id>/', views.edit_ingredient, name='edit_ingredient'),
    # PAGE FOR ADDING QUANTITY
    path('recipes/<int:recipe_id>/<int:ingredient_id>/add_quantity', views.quantity, name='add_quantity'),
    # PAGE FOR EDITING QUANTITY
    path('recipes/<int:recipe_id>/<int:ingredient_id>/edit_quantity', views.edit_quantity, name='edit_quantity'),
]

users/urls.py
"""Defines URL patterns for users"""

from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    # INCLUDE DEFAULT AUTH URLS
    path('', include('django.contrib.auth.urls')),
    # REGISTRATION PAGE
    path('register/', views.register, name='register'),
]

recipes/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings


class Recipe(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=500)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.title}'


class Ingredient(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    ingredient_type = models.CharField(max_length=50)

    class Meta:
        verbose_name_plural = 'ingredients'

    def __str__(self):
        return f'{self.name}, {self.ingredient_type}'


class Quantity(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
    ml_oz = models.IntegerField(max_length=5, null=True, blank=True)
    pieces = models.IntegerField(max_length=5, null=True, blank=True)
    dashes = models.IntegerField(max_length=5, null=True, blank=True)
    shake = models.BooleanField(default=True)

    class Meta:
        verbose_name_plural = 'quantities'

    def __str__(self):
        return f'{self.ml_oz}, {self.pieces}, {self.dashes}, {self.shake}'

recipes/forms.py
from django import forms
from .models import Recipe, Ingredient, Quantity


class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['title', 'description']
        labels = {'title': 'Title:', 'description': 'Description'}


class IngredientForm(forms.ModelForm):
    class Meta:
        model = Ingredient
        fields = ['name']
        labels = {'name': 'Ingredient:', 'Type': 'ingredient_type'}


class QuantityForm(forms.ModelForm):
    class Meta:
        model = Quantity
        fields = ['ml_oz']
        labels = {'Ml:': 'ml_oz:'}

recipes/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from .models import Recipe, Ingredient, Quantity
from .forms import RecipeForm, IngredientForm, QuantityForm


def index(request):
    """The home page for recipes"""
    return render(request, 'recipes/index.html')


def recipes(request):
    """Show all recipes """
    recipes = Recipe.objects.order_by('created_date')
    context = {'recipes': recipes}
    return render(request, 'recipes/recipes.html', context)


def recipe(request, recipe_id):
    """Show a single recipe and all its ingredients"""
    recipe = Recipe.objects.get(id=recipe_id)
    ingredients = recipe.ingredient_set.all()
    quantities = recipe.quantity_set.all()
    zipped = zip(ingredients, quantities)
    context = {'recipe': recipe, 'ingredients': ingredients, 'quantities': quantities, 'zipped': zipped}
    return render(request, 'recipes/recipe.html', context)


@login_required
def new_recipe(request):
    """Add a new recipe"""
    if request.method != 'POST':
        """Return blank form since no data is submitted - 'GET' method"""
        form = RecipeForm()
    else:
        """Process data since 'POST' method"""
        form = RecipeForm(data=request.POST)
        if form.is_valid():
            form.save()
            recipe = Recipe.objects.last()
            recipe.author = request.user
            form = IngredientForm()
            context = {'recipe': recipe, 'form': form}
            return render(request, 'recipes/new_ingredient.html', context)
    """Blank or invalid form"""
    context = {'form': form}
    return render(request, 'recipes/new_recipe.html', context)


@login_required
def edit_recipe(request, recipe_id):
    recipe = Recipe.objects.get(id=recipe_id)
    ingredients = recipe.ingredient_set.all()
    quantities = recipe.quantity_set.all()
    zipped = zip(ingredients, quantities)
    if request.method != 'POST':
        """Return blank form since no data is submitted - 'GET' method"""
        form = RecipeForm()
    else:
        """POST data submitted; process data"""
        form = RecipeForm(data=request.POST)
        if form.is_valid():
            form.save(commit=False)
            return redirect('recipes:recipe', recipe_id=recipe.id)

    context = {'recipe': recipe, 'ingredients': ingredients, 'quantities': quantities, 'zipped': zipped}
    return render(request, 'recipes/edit_recipe.html', context)


@login_required
def new_ingredient(request, recipe_id):
    """Add a new ingredient for particular recipe"""
    recipe = Recipe.objects.get(id=recipe_id)

    if request.method != 'POST':
        """Return blank form since no data is submitted - 'GET' method"""
        form = IngredientForm()
    else:
        """Process data since 'POST' method"""
        form = IngredientForm(data=request.POST)
        if form.is_valid():
            new_ingredient_form = form.save(commit=False)
            new_ingredient_form.recipe = recipe
            new_ingredient_form.save()
            ingredient = Ingredient.objects.last().id
            form = QuantityForm()
            context = {'recipe': recipe, 'ingredient': ingredient, 'form': form}
            return render(request, 'recipes/add_quantity.html', context)
    """Blank or invalid form"""
    context = {'recipe': recipe, 'form': form}
    return render(request, 'recipes/new_ingredient.html', context)


@login_required
def edit_ingredient(request, ingredient_id):
    """Edit an existing ingredient"""
    ingredient = Ingredient.objects.get(id=ingredient_id)
    recipe = ingredient.recipe

    if request.method != 'POST':
        """Initial request; Pre-fill form with the current entry so the user can edit it"""
        form = IngredientForm(instance=ingredient)
    else:
        """POST data submitted; process data"""
        form = IngredientForm(instance=ingredient, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('recipes:recipe', recipe_id=recipe.id)

    context = {'ingredient': ingredient, 'recipe': recipe, 'form': form}
    return render(request, 'recipes/edit_ingredient.html', context)


@login_required
def quantity(request, recipe_id, ingredient_id):
    """Add quantity for particular recipe and ingredient"""
    recipe = Recipe.objects.get(id=recipe_id)
    ingredient = Ingredient.objects.get(id=ingredient_id)

    if request.method != 'POST':
        """Return blank form since no data is submitted - 'GET' method"""
        form = QuantityForm()
    else:
        """Process data since 'POST' method"""
        form = QuantityForm(data=request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.recipe = recipe
            form.ingredient = ingredient
            form.save()
            return redirect('recipes:recipe', recipe_id=recipe_id)
    """Blank or invalid form"""
    context = {'recipe': recipe, 'ingredient': ingredient, 'form': form}
    return render(request, 'recipes/add_quantity.html', context)


@login_required
def edit_quantity(request, recipe_id, ingredient_id):
    """Edit an existing ingredient"""
    recipe = Recipe.objects.get(id=recipe_id)
    ingredient = Ingredient.objects.get(id=ingredient_id)
    quantity = get_object_or_404(Quantity, recipe_id=recipe_id, ingredient_id=ingredient_id)

    if request.method != 'POST':
        """Initial request; Pre-fill form with the current entry so the user can edit it"""
        form = QuantityForm(instance=quantity)
    else:
        """POST data submitted; process data"""
        form = QuantityForm(request.POST, instance=quantity)
        if form.is_valid():
            form.save()
            return redirect('recipes:recipe', recipe_id=recipe.id)

    context = {'recipe': recipe, 'ingredient': ingredient, 'quantity': quantity, 'form': form}
    return render(request, 'recipes/edit_quantity.html', context)

recipes/templates/recipes/add_quantity.html
{% extends "recipes/base.html" %}

{% load crispy_forms_tags %}

{% block content %}

 <p><a href="{% url 'recipes:recipe' recipe.id %}">{{ recipe }}</a></p>

 <p>Add quantity - ml/oz:</p>
 <form action="{% url 'recipes:add_quantity' recipe.id ingredient %}" method="POST">
     {% csrf_token %}
     {{ form|crispy }}
     <button name="Submit" class="btn btn-lg btn-outline-dark">Add quantity</button>
 </form>

{% endblock content %}

recipes/templates/recipes/base.html
<!DOCTYPE html>
{% load bootstrap4 %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>
        Viva la alcoholution!
    </title>
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
</head>

<body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-2 border">
        
        <a class="navbar-brand" href="{% url 'recipes:recipes' %}">Recipes</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon">
            </span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarCollapse">
            
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'recipes:index' %}">Home</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <span class="navbar-text">Hello, {{ user.username }}.</span>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
                </li>
                {% endif %}
            </ul>
        </div>
        
</nav>

<main role="main" class="container">
    <div class="pb-2 mb-2 border-bottom">
        {% block page_header %}{% endblock page_header %}
    </div>
    <div>
        {% block content %}{% endblock content %}
    </div>
</main>

</body>

</html>

recipes/templates/recipes/edit_ingredient.html
{% extends "recipes/base.html" %}

{% load crispy_forms_tags %}

{% block content %}

<p><a href="{% url 'recipes:recipe' recipe.id %}">{{ recipe }}</a></p>

<p>Edit ingredient:</p>
<form action="{% url 'recipes:edit_ingredient' ingredient.id %}" method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button name="Submit" class="btn btn-lg btn-outline-dark">Save changes</button>
</form>

{% endblock content %}

recipes/templates/recipes/edit_quantity.html
{% extends "recipes/base.html" %}

{% load crispy_forms_tags %}

{% block content %}

<p><a href="{% url 'recipes:recipe' recipe.id %}">{{ recipe }}</a></p>

<p>Edit quantity:</p>
<form action="{% url 'recipes:edit_quantity' recipe.id ingredient.id %}" method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button name="Submit" class="btn btn-lg btn-outline-dark">Save changes</button>
</form>

{% endblock content %}

recipes/templates/recipes/edit_recipe.html
{% extends "recipes/base.html" %}

{% block page_header %}

    <h1 class="display-4 mb-1">
        {{ recipe }}:
    </h1>
{% endblock page_header %}

{% block content %}

<div>
	<img class="card-group mb-2" src="https://i.pinimg.com/originals/3f/97/b3/3f97b30892916d3ef91618529f48f0a4.jpg" style="height:200px; width=80px;" alt="Cocktail picture here">
	<ul class="list-group list-group-flush mb-2 pb-1">
		{% for i , q in zipped %}
		{{ q.ml_oz }} ml of {{ i.name }}
			<li style="list-style-type: none;">
				<p>
					<a href="{% url 'recipes:edit_ingredient' i.id %}">Edit ingredient</a><br>
					<a href="{% url 'recipes:edit_quantity' recipe.id i.id %}">Edit quantity</a>
				</p>
			</li>
		{% endfor %}
	</ul>
	
  <a href="{% url 'recipes:new_ingredient' recipe.id %}" class="btn btn-lg btn-outline-dark">Add new ingredient</a>
	
</div>

{% endblock content %}

recipes/templates/recipes/index.html
{% extends "recipes/base.html" %}

{% block page_header %}
    <div class="jumbotron mb-1" style="height: 290px;">
        <h1 class="display-4">
            Welcome to your favorite cocktail site!
        </h1>
        <p class="lead">
            Here you will be able to register as a user, add, update and check out number of cocktail recipes!
        </p>

        <p class="lead">
            Viva la alcoholution!
        </p>
        <a class="btn btn-lg btn-outline-dark" href="{% url 'users:register' %}" role="button">
            Register &raquo;
        </a>
    </div>
{% endblock page_header %}

{% block content %}
<div class="card mb-1">
    <img class="card-img-top" style="height: 550px;" src="https://img.thedailybeast.com/image/upload/c_crop,d_placeholder_euli9k,h_1440,w_2560,x_0,y_0/dpr_1.5/c_limit,w_1044/fl_lossy,q_auto/v1517521303/180131-wondrich-bad-cocktail-tease_wghhv8" alt="Background image missing.">
</div>
{% endblock content %}

recipes/templates/recipes/new_ingredient.html
{% extends "recipes/base.html" %}

{% load crispy_forms_tags %}

{% block content %}

 <p><a href="{% url 'recipes:recipe' recipe.id %}">{{ recipe }}</a></p>

 <p>Add a new ingredient:</p>
 <form action="{% url 'recipes:new_ingredient' recipe.id %}" method="POST">
     {% csrf_token %}
     {{ form|crispy }}
     <button name="Submit" class="btn btn-lg btn-outline-dark">Add ingredient</button>
 </form>

{% endblock content %}

recipes/templates/recipes/new_recipe.html
{% extends "recipes/base.html" %}

{% load crispy_forms_tags %}

{% block content %}
<p>Add a new recipe:</p>

<form action="{% url 'recipes:new_recipe' %}" method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button name="Submit" class="btn btn-lg btn-outline-dark">Add recipe</button>
</form>

{% endblock content %}

recipes/templates/recipes/recipe.html
{% extends "recipes/base.html" %}

{% block page_header %}

    <h1 class="display-4 mb-1">
        {{ recipe }}:
    </h1>
{% endblock page_header %}

{% block content %}

<div>
	<img class="card-group mb-2" src="https://i.pinimg.com/originals/3f/97/b3/3f97b30892916d3ef91618529f48f0a4.jpg" style="height:200px; width=80px;" alt="Cocktail picture here">
	<ul class="list-group list-group-flush mb-2 pb-1">
		{% for i , q in zipped %}
		{{ q.ml_oz }} ml of {{ i.name }}
			<li style="list-style-type: none;">
				<p>
					<a href="{% url 'recipes:edit_ingredient' i.id %}">Edit ingredient</a><br>
					<a href="{% url 'recipes:edit_quantity' recipe.id i.id %}">Edit quantity</a>
				</p>
			</li>
		{% endfor %}
	</ul>
	
  <a href="{% url 'recipes:new_ingredient' recipe.id %}" class="btn btn-lg btn-outline-dark">Add new ingredient</a>
	
</div>

{% endblock content %}

recipes/templates/recipes/recipes.html
{% extends "recipes/base.html" %}

{% block page_header %}
    <h1 class="display-4">
        Recipes:
    </h1>
{% endblock page_header %}

{% block content %}

<div class="card-deck">
    {% for recipe in recipes %}
    <div class="row row-cols-4">
        <div class="col">
            <div class="card mb-2" style="width: 16rem;">
                <img src="https://i.pinimg.com/originals/3f/97/b3/3f97b30892916d3ef91618529f48f0a4.jpg" class="card-img-top" alt="Cocktail picture here">
                    <div class="card-body">
                        <a class=" card-title btn btn-lg btn-outline-dark" href="{% url 'recipes:recipe' recipe.id %}">
                            {{ recipe }}
                        </a>
                        <p class="card-text">{{ recipe.description }}.</p>
                    </div>
            </div>
        </div>
    </div>
    
    {% empty %}
        <li>
            No recipes have been added yet.
        </li>
    {% endfor %}
</div>

<a href="{% url 'recipes:new_recipe' %}" class="btn btn-lg btn-outline-dark" >Add a new recipe</a>
{% endblock content %}